### PR TITLE
canvas read/write + multiplayer overwrite bug fix

### LINKED ISSUE #10905: misplaced canvas write in multiplayer
### Platforms

Windows

### Build

b149β

### Issue

I try to write to a canvas at the same time as someone else and my canvas gets replaced by theirs

### Steps to reproduce

1. place 2 canvases
2. P2 open canvas 2
3. P1 open canvas 1
4. P1 draw to canvas 1
5. P1 exit canvas 1
6. P2 mark canvas 2 as modified
7. P2 exit canvas 2
→ canvas 2 ends up like canvas 1, except for P2's modifications

### Mods used

_No response_

### Save file

_No response_

### (Crash) logs

_No response_

### Submission

- [x] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [x] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

### PR DESCRIPTION
**Pull request by The4codeblocks**
adds:
read/write to canvases
sense canvas width/height (does not include connections)

also should fix #10905

also patched a leak where the texture doesn't get freed when cancelling / pressing ok with no modification / backing out

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java [hunk 1]
```diff
@@ -49,7 +50,9 @@ public CanvasBlock(String name){
 
         config(byte[].class, (CanvasBuild build, byte[] bytes) -> {
             if(build.data.length == bytes.length){
-                build.data = bytes;
+                for(int i = 0; i < bytes.length; ++i){
```
Comment (Redstonneur1256) [inline core/src/mindustry/world/blocks/logic/CanvasBlock.java]: Could use `System.arraycopy`

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java [hunk 2]
```diff
@@ -153,10 +153,38 @@ public class CanvasBuild extends Building{
         public byte[] data = new byte[Mathf.ceil(canvasSize * canvasSize * bitsPerPixel / 8f)];
         public int blending;
 
+        public void setPixel(int pos, int index){
+            if(pos < canvasSize * canvasSize && pos >= 0 && index >= 0 && index < palette.length){
+                setByte(data, pos * bitsPerPixel, index);
+                updateTexture();
```
Comment (Redstonneur1256) [inline core/src/mindustry/world/blocks/logic/CanvasBlock.java]: Redrawing the entire texture each time every update would result in unnecessary performance loss especially if the canvas is off screen, could use a flag to mark it was updated and have the texture updated when it's actually drawn

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java [hunk 3]
```diff
@@ -252,7 +288,7 @@ public void buildConfiguration(Table table){
             table.button(Icon.pencil, Styles.cleari, () -> {
                 Dialog dialog = new Dialog();
 
-                Pixmap pix = makePixmap(data);
+                Pixmap pix = makePixmap(data, new Pixmap(canvasSize, canvasSize));
```
Comment (Redstonneur1256) [inline core/src/mindustry/world/blocks/logic/CanvasBlock.java:292]: The Pixmap is never freed.

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java [hunk 4]
```diff
@@ -252,7 +288,7 @@ public void buildConfiguration(Table table){
...
                 Texture texture = new Texture(pix);
```
Comment (Redstonneur1256) [inline core/src/mindustry/world/blocks/logic/CanvasBlock.java:293]: Texture isn't disposed when cancelling the edit.

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java [hunk 5]
```diff
@@ -65,13 +68,15 @@ public void init(){
         bitsPerPixel = Mathf.log2(Mathf.nextPowerOfTwo(palette.length));
 
         clipSize = Math.max(clipSize, size * 8 - padding);
+
+        previewPixmap = new Pixmap(canvasSize, canvasSize);
```
Comment (Redstonneur1256) [inline core/src/mindustry/world/blocks/logic/CanvasBlock.java:70]: The Pixmap is never freed when the block is removed.

**Review by Redstonneur1256 — CHANGES_REQUESTED** [review]

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java (hunk 2 above)
Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java]: had the same idea though I didn't implement it

Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java]: should be done in https://github.com/Anuken/Mindustry/pull/10899/commits/012a8f08d5b5137256581b85f20b45455e6e2abf

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java (hunk 5 above)
Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java:70]: when do you remove blocks (content instances) during runtime anyway?

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java (hunk 4 above)
Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java:293]: I don't think I touched the texture so that's not part of my PR

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java (hunk 3 above)
Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java:292]: should be done in https://github.com/Anuken/Mindustry/pull/10899/commits/96f6a3cbcb4a89d851f2033f62989d33ffec861a

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java (hunk 4 above)
Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java:293]: should be done in https://github.com/Anuken/Mindustry/pull/10899/commits/96f6a3cbcb4a89d851f2033f62989d33ffec861a

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java (hunk 1 above)
Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java]: should be done in https://github.com/Anuken/Mindustry/pull/10899/commits/14f5af58ac2df4d85a9feecb4cb2d88509a84a0a

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java (hunk 5 above)
Comment (Redstonneur1256) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java:70]: When the block is destroyed/deconstructed the `remove()` method is called (see logic displays for example)

Comment (Redstonneur1256) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java:70]: My bad, I have misread it, I thought this was in the build class and not the block, this should be fine as is.

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java [hunk 6]
```diff
@@ -252,13 +288,17 @@ public void buildConfiguration(Table table){
...
-                Pixmap pix = makePixmap(data);
+                Pixmap pix = makePixmap(data, new Pixmap(canvasSize, canvasSize));
                 Texture texture = new Texture(pix);
                 int[] curColor = {palette[0]};
                 boolean[] modified = {false};
                 boolean[] fill = {false};
 
-                dialog.resized(dialog::hide);
+                dialog.resized(() -> {
+                    texture.dispose();
```
Comment (Anuken) [inline core/src/mindustry/world/blocks/logic/CanvasBlock.java:299]: Instead of adding texture/pixmap disposing in 4 places, you should add a hide listener and do it there (`dialog.hidden(() => {})`)

Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java:299]: thanks
<sub>~~also are you sure that the suggested arrow notation is right?~~</sub>

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java [hunk 7]
```diff
@@ -388,14 +429,13 @@ public void draw(){
                     }).size(44f);
                 });
 
-                dialog.closeOnBack();
+                dialog.closeOnBack(dialog::hide);
```
Comment (Anuken) [inline core/src/mindustry/world/blocks/logic/CanvasBlock.java]: Why did you change this? Closing hides the dialog, you're just making it hide twice.

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java [hunk 8]
```diff
@@ -214,7 +242,7 @@ public void draw(){
                 super.draw();
             }
 
-            if(texture == null){
+            if(texture == null || updated){
```
Comment (Anuken) [inline core/src/mindustry/world/blocks/logic/CanvasBlock.java:245]: I don't see you setting `updated` to `false` anywhere, meaning it will update every frame once it's set.

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java (hunk 7 above)
Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java]: oh right yeah I just did a substitution, thanks
fixed in https://github.com/Anuken/Mindustry/pull/10899/commits/4a02b42c291f67c295eb4b9211c4711a8134ba08

File: core/src/mindustry/world/blocks/logic/CanvasBlock.java (hunk 8 above)
Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java:245]: oh right
fixed in https://github.com/Anuken/Mindustry/pull/10899/commits/4a02b42c291f67c295eb4b9211c4711a8134ba08

Comment (Anuken) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java:245]: You set `update`, not `updated`, which is *very* different (and will completely break the block)

Comment (The4codeblocks) [reply core/src/mindustry/world/blocks/logic/CanvasBlock.java:245]: > You set `update`, not `updated`

should be fixed in https://github.com/Anuken/Mindustry/pull/10899/commits/c4fab2d18e2463279cce034efae6bf64e948bb46
